/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SovereignAiRouteImport } from './routes/sovereign-ai'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LawgichubRouteImport } from './routes/lawgichub'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsManufacturingRouteImport } from './routes/solutions/manufacturing'
import { Route as SolutionsLegalRouteImport } from './routes/solutions/legal'
import { Route as SolutionsInfrastructureRouteImport } from './routes/solutions/infrastructure'
import { Route as SolutionsEngineeringRouteImport } from './routes/solutions/engineering'
import { Route as SolutionsEnergyRouteImport } from './routes/solutions/energy'
import { Route as SolutionsConstructionRouteImport } from './routes/solutions/construction'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SovereignAiRoute = SovereignAiRouteImport.update({
  id: '/sovereign-ai',
  path: '/sovereign-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LawgichubRoute = LawgichubRouteImport.update({
  id: '/lawgichub',
  path: '/lawgichub',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsManufacturingRoute = SolutionsManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsLegalRoute = SolutionsLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsInfrastructureRoute = SolutionsInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsEngineeringRoute = SolutionsEngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsEnergyRoute = SolutionsEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsConstructionRoute = SolutionsConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/lawgichub': typeof LawgichubRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/sovereign-ai': typeof SovereignAiRoute
  '/trust': typeof TrustRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/energy': typeof SolutionsEnergyRoute
  '/solutions/engineering': typeof SolutionsEngineeringRoute
  '/solutions/infrastructure': typeof SolutionsInfrastructureRoute
  '/solutions/legal': typeof SolutionsLegalRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/lawgichub': typeof LawgichubRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/sovereign-ai': typeof SovereignAiRoute
  '/trust': typeof TrustRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/energy': typeof SolutionsEnergyRoute
  '/solutions/engineering': typeof SolutionsEngineeringRoute
  '/solutions/infrastructure': typeof SolutionsInfrastructureRoute
  '/solutions/legal': typeof SolutionsLegalRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/lawgichub': typeof LawgichubRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/sovereign-ai': typeof SovereignAiRoute
  '/trust': typeof TrustRoute
  '/solutions/construction': typeof SolutionsConstructionRoute
  '/solutions/energy': typeof SolutionsEnergyRoute
  '/solutions/engineering': typeof SolutionsEngineeringRoute
  '/solutions/infrastructure': typeof SolutionsInfrastructureRoute
  '/solutions/legal': typeof SolutionsLegalRoute
  '/solutions/manufacturing': typeof SolutionsManufacturingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/contact'
    | '/insights'
    | '/lawgichub'
    | '/platform'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/solutions'
    | '/sovereign-ai'
    | '/trust'
    | '/solutions/construction'
    | '/solutions/energy'
    | '/solutions/engineering'
    | '/solutions/infrastructure'
    | '/solutions/legal'
    | '/solutions/manufacturing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/contact'
    | '/insights'
    | '/lawgichub'
    | '/platform'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/solutions'
    | '/sovereign-ai'
    | '/trust'
    | '/solutions/construction'
    | '/solutions/energy'
    | '/solutions/engineering'
    | '/solutions/infrastructure'
    | '/solutions/legal'
    | '/solutions/manufacturing'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/contact'
    | '/insights'
    | '/lawgichub'
    | '/platform'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/solutions'
    | '/sovereign-ai'
    | '/trust'
    | '/solutions/construction'
    | '/solutions/energy'
    | '/solutions/engineering'
    | '/solutions/infrastructure'
    | '/solutions/legal'
    | '/solutions/manufacturing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  LawgichubRoute: typeof LawgichubRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  SovereignAiRoute: typeof SovereignAiRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sovereign-ai': {
      id: '/sovereign-ai'
      path: '/sovereign-ai'
      fullPath: '/sovereign-ai'
      preLoaderRoute: typeof SovereignAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawgichub': {
      id: '/lawgichub'
      path: '/lawgichub'
      fullPath: '/lawgichub'
      preLoaderRoute: typeof LawgichubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/manufacturing': {
      id: '/solutions/manufacturing'
      path: '/manufacturing'
      fullPath: '/solutions/manufacturing'
      preLoaderRoute: typeof SolutionsManufacturingRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/legal': {
      id: '/solutions/legal'
      path: '/legal'
      fullPath: '/solutions/legal'
      preLoaderRoute: typeof SolutionsLegalRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/infrastructure': {
      id: '/solutions/infrastructure'
      path: '/infrastructure'
      fullPath: '/solutions/infrastructure'
      preLoaderRoute: typeof SolutionsInfrastructureRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/engineering': {
      id: '/solutions/engineering'
      path: '/engineering'
      fullPath: '/solutions/engineering'
      preLoaderRoute: typeof SolutionsEngineeringRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/energy': {
      id: '/solutions/energy'
      path: '/energy'
      fullPath: '/solutions/energy'
      preLoaderRoute: typeof SolutionsEnergyRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/construction': {
      id: '/solutions/construction'
      path: '/construction'
      fullPath: '/solutions/construction'
      preLoaderRoute: typeof SolutionsConstructionRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsConstructionRoute: typeof SolutionsConstructionRoute
  SolutionsEnergyRoute: typeof SolutionsEnergyRoute
  SolutionsEngineeringRoute: typeof SolutionsEngineeringRoute
  SolutionsInfrastructureRoute: typeof SolutionsInfrastructureRoute
  SolutionsLegalRoute: typeof SolutionsLegalRoute
  SolutionsManufacturingRoute: typeof SolutionsManufacturingRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsConstructionRoute: SolutionsConstructionRoute,
  SolutionsEnergyRoute: SolutionsEnergyRoute,
  SolutionsEngineeringRoute: SolutionsEngineeringRoute,
  SolutionsInfrastructureRoute: SolutionsInfrastructureRoute,
  SolutionsLegalRoute: SolutionsLegalRoute,
  SolutionsManufacturingRoute: SolutionsManufacturingRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  LawgichubRoute: LawgichubRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  SovereignAiRoute: SovereignAiRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
